opts=testF.simulate_options()

opts['filter']=['middleMostFinger.fingerStructure.doubleBoneJoint.twoDegreeJoint.restrainedRevolute1.revolute.axis.phi',
'middleMostFinger.fingerStructure.doubleBoneJoint.twoDegreeJoint.restrainedRevolute.revolute.axis.phi',
'middleMostFinger.fingerStructure.boneJoint.joint.restrainedRevolute.revolute.axis.phi',
'middleMostFinger.fingerStructure.boneJoint1.joint.restrainedRevolute.revolute.axis.phi','middleMostFinger.objectConnection2.contact',
'middleMostFinger.objectConnection1.contact','middleMostFinger.objectConnection.contact',
'middleRightFinger.fingerStructure.doubleBoneJoint.twoDegreeJoint.restrainedRevolute1.revolute.axis.phi',
'middleRightFinger.fingerStructure.doubleBoneJoint.twoDegreeJoint.restrainedRevolute.revolute.axis.phi',
'middleRightFinger.fingerStructure.boneJoint.joint.restrainedRevolute.revolute.axis.phi',
'middleRightFinger.fingerStructure.boneJoint1.joint.restrainedRevolute.revolute.axis.phi',
'middleRightFinger.objectConnection2.contact','middleRightFinger.objectConnection1.contact','middleRightFinger.objectConnection.contact',
'middleLeftFinger.fingerStructure.doubleBoneJoint.twoDegreeJoint.restrainedRevolute1.revolute.axis.phi',
'middleLeftFinger.fingerStructure.doubleBoneJoint.twoDegreeJoint.restrainedRevolute.revolute.axis.phi',
'middleLeftFinger.fingerStructure.boneJoint.joint.restrainedRevolute.revolute.axis.phi',
'middleLeftFinger.fingerStructure.boneJoint1.joint.restrainedRevolute.revolute.axis.phi',
'middleLeftFinger.objectConnection2.contact','middleLeftFinger.objectConnection1.contact','middleLeftFinger.objectConnection.contact',
'opposable.fingerStructure.doubleBoneJoint.twoDegreeJoint.restrainedRevolute1.revolute.axis.phi',
'opposable.fingerStructure.doubleBoneJoint.twoDegreeJoint.restrainedRevolute.revolute.axis.phi',
'opposable.fingerStructure.boneJoint.joint.restrainedRevolute.revolute.axis.phi',
'opposable.fingerStructure.boneJoint1.joint.restrainedRevolute.revolute.axis.phi',
'opposable.objectConnection2.contact','opposable.objectConnection1.contact','opposable.objectConnection.contact',
'leftMostFinger.fingerStructure.doubleBoneJoint.twoDegreeJoint.restrainedRevolute1.revolute.axis.phi',
'leftMostFinger.fingerStructure.doubleBoneJoint.twoDegreeJoint.restrainedRevolute.revolute.axis.phi',
'leftMostFinger.fingerStructure.boneJoint.joint.restrainedRevolute.revolute.axis.phi',
'leftMostFinger.fingerStructure.boneJoint1.joint.restrainedRevolute.revolute.axis.phi',
'leftMostFinger.objectConnection2.contact','leftMostFinger.objectConnection1.contact','leftMostFinger.objectConnection.contact']

tF=testF.simulate(final_time=20,options=opts)